# create a datatable with long names for table
stvariable_names <- data.frame(VAR = c( "Hypertension", "CHF", "OtherCardio", 
                                        "ChrnLung", "ChrRenal", "ChrLvr", 
                                        "Diabetes", "Obesity", "HIV_AIDS", 
                                        "RheumArth", "Lupus", "Anemia", 
                                        "Cancer", "Alcuse", "Tobacco", 
                                        "Cerclage", "MultiGest", "GestDiab", 
                                        "GestHyper", "Preeclampsia", 
                                        "Eclampsia", "Abruption", 
                                        "AnteHemorrhage", "PreRuptMem", 
                                        "PretermLab", "PretermDel", "Induced", 
                                        "Prolonged", "Artificial", "Stillbirth",
                                        "PostHemorrage", "Retained", "Vaginal", 
                                        "AssistVag", "Cesarean", "UnkMode", 
                                        "Puerperal", "Chorioamnionitis", 
                                        "Endometritis", "SepAbortion", 
                                        "InfParDis", "Respiratory", 
                                        "Genitourinary", "Digestive", "Wound", 
                                        "Bacteremia", "Circulatory", "Nervous", 
                                        "CLABSI", "Mastitis", "Musculoskeletal",
                                        "Other", "Hemodialysis", "PosPresVent", 
                                        "CentLine",  "Hemodynamic", 
                                        "Transfusion", "Hysterectomy", 
                                        "Surgical","RespFail", "CardioFail", 
                                        "RenalFail", "HepFail", "BloodFail", 
                                        "NeuroFail", "Abortion", "Antepartum", 
                                        "Delivery",  "Postpartum", "Unknown"), 
                               Long_Names = c('\\ Hypertension', 
                                              '\\ Congestive Heart Failure', 
                                              '\\ Other Cardiovascular Disease', 
                                              '\\ Chronic Pulmonary Disease', 
                                              '\\ Renal Disease', 
                                              '\\ Liver Disease', 
                                              '\\ Diabetes mellitus',
                                              '\\ Obesity', 
                                              '\\ HIV/AIDS', 
                                              '\\ Rheumatoid Arthritis or Collagen Vascular Disease', 
                                              '\\ Systemic lupus erythematosus', 
                                              '\\ Anemia', 
                                              '\\ Cancer', 
                                              '\\ Alcohol or Substance Abuse', 
                                              '\\ Tobacco Use',
                                              '\\ Cerclage', 
                                              '\\ Multiple Gestation', 
                                              '\\ Gestational Diabetes', 
                                              '\\ Gestational Hypertension', 
                                              '\\ Pre-eclampsia', 
                                              '\\ Eclampsia', 
                                              '\\ Placental Abruption', 
                                              '\\ Antepartum Hemorrhage',
                                              '\\ Premature Ruprture of Membranes', 
                                              '\\ Preterm Labor (excl Preterm Delivery)', 
                                              '\\ Preterm Delivery',
                                              '\\ Induction of Labour',
                                              '\\ Prolonged Rupture of Membranes/ Prolonged Labour',
                                              '\\ Artificial Ruprture of Membranes', 
                                              '\\ Stillbirth',
                                              '\\ Postpartum Hemorrhage', 
                                              '\\ Retained Products of Conception',
                                              '\\ Vaginal Delivery', 
                                              '\\ Assisted Vaginal Delivery', 
                                              '\\ Cesarean Section', 
                                              '\\ Unknown',
                                              '\\ Puerperal Infection', 
                                              '\\ Chorioamnionitis', 
                                              '\\ Endometritis', 
                                              '\\ Septic Abortion', 
                                              '\\ Infectious and Parasitic Diseases', 
                                              '\\ Respiratory', 
                                              '\\ Genitourinary', 
                                              '\\ Digestive', 
                                              '\\ Wound, Skin, or Soft Tissue Infection', 
                                              '\\ Bacteremia', 
                                              '\\ Circulatory', 
                                              '\\ Nervous', 
                                              '\\ CLABSI', 
                                              '\\ Mastitis', 
                                              '\\ Musculoskeletal', 
                                              '\\ Other',
                                              '\\ Hemodialysis', 
                                              '\\ Positive Pressure Ventilation', 
                                              '\\ Central Line Placement', 
                                              '\\ Invasive Hemodynamic Monitoring', 
                                              '\\ Blood Transfusion', 
                                              '\\ Hysterectomy', 
                                              '\\ Surgical Intervention (excluding Obstetrical Procedures)',
                                              '\\ Respiratory', 
                                              '\\ Cardiovascular', 
                                              '\\ Renal', 
                                              '\\ Hepatic', 
                                              '\\ Hematological/Coagulation', 
                                              '\\ Neurological', 
                                              '\\ Abortion or Fetal loss', 
                                              '\\ Antepartum', 
                                              '\\ Delivery', 
                                              '\\ Postpartum', 
                                              '\\ Unknown'))

save(stvariable_names, file = 'DataProcessed\string_variable_names.rda')